version: '3'

services:
  energy-prediction:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./static:/app/static
    restart: unless-stopped
    environment:
      - FLASK_ENV=production